package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.Commodity;
import com.paul.logisticsmanagementsystem.entity.CommodityExample;
import java.util.List;

import com.paul.logisticsmanagementsystem.entity.CompleteCommodity;
import org.apache.ibatis.annotations.Param;

public interface CommodityMapper {


    CompleteCommodity getCompleteCommodityById(@Param("commodityid") Integer commodityid);

    List<CompleteCommodity> getAllCommodity(@Param("goodsname") String goodsname, @Param("ordercode") String ordercode, @Param("logisticcode") String logisticcode,@Param("username") String username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    long countByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    int deleteByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    int deleteByPrimaryKey(Integer commodityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    int insertSelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    List<Commodity> selectByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    Commodity selectByPrimaryKey(Integer commodityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    int updateByExample(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    int updateByPrimaryKeySelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    int updateByPrimaryKey(Commodity record);
}