package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.GeneralUser;

import java.util.*;
import org.apache.ibatis.annotations.Param;

public interface GeneralUserMapper {

    GeneralUser  verifyGeneralUserByIdNumber(@Param("idnumber") String idnumber);
    GeneralUser  verifyGeneralUserByPhone(@Param("phone") String phone);
    GeneralUser  verifyGeneralUserByUserName(@Param("username") String username);
    GeneralUser  verifyGeneralUserByEmail(@Param("email") String email);

    HashMap<String,String> getLoginTypeByUserName(@Param("username") String username);

    GeneralUser verifyGeneralUser(@Param("username") String username, @Param("password") String password);

    List<GeneralUser> getSelectiveGeneralUser(@Param("username") String username);

    GeneralUser getGeneralUser(@Param("username") String username, @Param("password") String password,@Param("logintype") String logintype);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generaluser
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generaluser
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generaluser
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    int insert(GeneralUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generaluser
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    int insertSelective(GeneralUser record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generaluser
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    GeneralUser selectByPrimaryKey(Integer userid);

    /*获取所有个人用户*/
    List<GeneralUser> getAllGeneralUsers(@Param("username") String username, @Param("phone") String phone,@Param("sex") String sex,@Param("idnumber") String idnumber,@Param("logintype") String logintype);





    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generaluser
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    int updateByPrimaryKeySelective(GeneralUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generaluser
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    int updateByPrimaryKey(GeneralUser record);


}