package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.CompleteOrder;
import com.paul.logisticsmanagementsystem.entity.Orders;
import com.paul.logisticsmanagementsystem.entity.OrdersExample;
import java.util.*;


import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {

    HashMap<String,String>  selectStateById(@Param("orderid") Integer orderid);

    List<CompleteOrder> getSelectiveTraces(@Param("logisticcode") String logisticcode, @Param("ordercode") String ordercode, @Param("senderphone") String senderphone, @Param("receiverphone") String receiverphone);

    List<CompleteOrder> getAllCompleteOrders();

    CompleteOrder getAllCompleteOrdersByOrderid(@Param("orderid") Integer orderid);

    List<Orders> getAllOrders(@Param("ordercode") String ordercode,@Param("logisticcode") String logisticcode,@Param("state") String state,@Param("orderstate") String orderstate,@Param("goodsname") String goodsname,@Param("startDate") String startDate,@Param("endDate") String endDate);

    List<Orders> getSelectiveOrders(@Param("ordercode") String ordercode,@Param("logisticcode") String logisticcode,@Param("state") String state,@Param("orderstate") String orderstate,@Param("goodsname") String goodsname,@Param("userid") Integer userid,@Param("startDate") String startDate,@Param("endDate") String endDate);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    Orders selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    int updateByPrimaryKeySelective(Orders record);


    void updateOrderStateByState(Orders orders);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue May 22 19:17:33 CST 2018
     */
    int updateByPrimaryKey(Orders record);
}