package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.Sender;
import com.paul.logisticsmanagementsystem.entity.SenderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SenderMapper {


    int selectSenderIdByMark(@Param("mark") String mark);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    long countByExample(SenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    int deleteByExample(SenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    int deleteByPrimaryKey(@Param("senderid") Integer senderid, @Param("userid") Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    int insert(Sender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    int insertSelective(Sender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    List<Sender> selectByExample(SenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    Sender selectByPrimaryKey(@Param("senderid") Integer senderid, @Param("userid") Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sender record, @Param("example") SenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    int updateByExample(@Param("record") Sender record, @Param("example") SenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    int updateByPrimaryKeySelective(Sender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    int updateByPrimaryKey(Sender record);
}