package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.SubMenu;
import com.paul.logisticsmanagementsystem.entity.SubMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    long countByExample(SubMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    int deleteByExample(SubMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    int deleteByPrimaryKey(Integer submenuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    int insert(SubMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    int insertSelective(SubMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    List<SubMenu> selectByExample(SubMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    SubMenu selectByPrimaryKey(Integer submenuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") SubMenu record, @Param("example") SubMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    int updateByExample(@Param("record") SubMenu record, @Param("example") SubMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    int updateByPrimaryKeySelective(SubMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    int updateByPrimaryKey(SubMenu record);
}