package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.SystemNotification;
import com.paul.logisticsmanagementsystem.entity.SystemNotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemNotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    long countByExample(SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int deleteByExample(SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int insert(SystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int insertSelective(SystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    List<SystemNotification> selectByExample(SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    SystemNotification selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") SystemNotification record, @Param("example") SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByExample(@Param("record") SystemNotification record, @Param("example") SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByPrimaryKeySelective(SystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemnotification
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByPrimaryKey(SystemNotification record);
}