package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.TracesReservation;
import com.paul.logisticsmanagementsystem.entity.TracesReservationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TracesReservationMapper {

     List<TracesReservation> selectByOrderId(@Param("id") Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    long countByExample(TracesReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    int deleteByExample(TracesReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    int deleteByPrimaryKey(Integer tracesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    int insert(TracesReservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    int insertSelective(TracesReservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    List<TracesReservation> selectByExample(TracesReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    TracesReservation selectByPrimaryKey(Integer tracesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") TracesReservation record, @Param("example") TracesReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    int updateByExample(@Param("record") TracesReservation record, @Param("example") TracesReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    int updateByPrimaryKeySelective(TracesReservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    int updateByPrimaryKey(TracesReservation record);
}