package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.Traces;
import com.paul.logisticsmanagementsystem.entity.TracesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TracesMapper {
    void deleteTracesByOrderId(@Param("orderid") Integer orderid);

    List<Traces> selectByOrderId(@Param("orderid") Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    long countByExample(TracesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int deleteByExample(TracesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int deleteByPrimaryKey(Integer tracesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int insert(Traces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int insertSelective(Traces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    List<Traces> selectByExample(TracesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    Traces selectByPrimaryKey(Integer tracesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") Traces record, @Param("example") TracesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByExample(@Param("record") Traces record, @Param("example") TracesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByPrimaryKeySelective(Traces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traces
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByPrimaryKey(Traces record);
}