package com.paul.logisticsmanagementsystem.mapper;

import com.paul.logisticsmanagementsystem.entity.TransactionLocation;
import com.paul.logisticsmanagementsystem.entity.TransactionLocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    long countByExample(TransactionLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int deleteByExample(TransactionLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int deleteByPrimaryKey(Integer tlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int insert(TransactionLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int insertSelective(TransactionLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    List<TransactionLocation> selectByExample(TransactionLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    TransactionLocation selectByPrimaryKey(Integer tlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") TransactionLocation record, @Param("example") TransactionLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByExample(@Param("record") TransactionLocation record, @Param("example") TransactionLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByPrimaryKeySelective(TransactionLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactionlocation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    int updateByPrimaryKey(TransactionLocation record);
}