package com.paul.logisticsmanagementsystem.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminid
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.photo
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.age
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.sex
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.phone
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.email
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.idnumber
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private String idnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.logintype
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    private String logintype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public Admin(Integer adminid, String username, String password, String photo, Integer age, String sex, String phone, String email, String idnumber, String logintype) {
        this.adminid = adminid;
        this.username = username;
        this.password = password;
        this.photo = photo;
        this.age = age;
        this.sex = sex;
        this.phone = phone;
        this.email = email;
        this.idnumber = idnumber;
        this.logintype = logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public Admin() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminid
     *
     * @return the value of admin.adminid
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminid
     *
     * @param adminid the value for admin.adminid
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.photo
     *
     * @return the value of admin.photo
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.photo
     *
     * @param photo the value for admin.photo
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.age
     *
     * @return the value of admin.age
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.age
     *
     * @param age the value for admin.age
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.sex
     *
     * @return the value of admin.sex
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.sex
     *
     * @param sex the value for admin.sex
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.phone
     *
     * @return the value of admin.phone
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.phone
     *
     * @param phone the value for admin.phone
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.email
     *
     * @return the value of admin.email
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.email
     *
     * @param email the value for admin.email
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.idnumber
     *
     * @return the value of admin.idnumber
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.idnumber
     *
     * @param idnumber the value for admin.idnumber
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.logintype
     *
     * @return the value of admin.logintype
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public String getLogintype() {
        return logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.logintype
     *
     * @param logintype the value for admin.logintype
     *
     * @mbg.generated Wed May 16 11:11:27 CST 2018
     */
    public void setLogintype(String logintype) {
        this.logintype = logintype == null ? null : logintype.trim();
    }
}