package com.paul.logisticsmanagementsystem.entity;

import java.math.BigDecimal;

/**
 * created with IntelliJ IDEA
 * User: FengZhi
 * Date: 5/9/2018
 * Time: 10:23 PM
 * Email:2045532295@qq.com
 * Addres:zhbit
 * Description:
 */
public class CompleteCommodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generaluser.userid
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generaluser.username
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generaluser.password
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generaluser.age
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generaluser.sex
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generaluser.phone
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generaluser.email
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generaluser.idnumber
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String idnumber;
    private String photo;
    private String logintype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityid
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private Integer commodityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.goodsName
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.goodsPhoto
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private String goodsphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.goodsQuantity
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private Integer goodsquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.goodsWeight
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private BigDecimal goodsweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.goodsDesc
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private String goodsdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.cost
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.orderCode
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private String ordercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.logisticCode
     *
     * @mbg.generated Wed May 09 20:28:25 CST 2018
     */
    private String logisticcode;

    public CompleteCommodity(Integer userid, String username, String password, Integer age, String sex, String phone, String email, String idnumber, String photo, String logintype, Integer commodityid, String goodsname, String goodsphoto, Integer goodsquantity, BigDecimal goodsweight, String goodsdesc, BigDecimal cost, String ordercode, String logisticcode) {
        this.userid = userid;
        this.username = username;
        this.password = password;
        this.age = age;
        this.sex = sex;
        this.phone = phone;
        this.email = email;
        this.idnumber = idnumber;
        this.photo = photo;
        this.logintype = logintype;
        this.commodityid = commodityid;
        this.goodsname = goodsname;
        this.goodsphoto = goodsphoto;
        this.goodsquantity = goodsquantity;
        this.goodsweight = goodsweight;
        this.goodsdesc = goodsdesc;
        this.cost = cost;
        this.ordercode = ordercode;
        this.logisticcode = logisticcode;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getIdnumber() {
        return idnumber;
    }

    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getLogintype() {
        return logintype;
    }

    public void setLogintype(String logintype) {
        this.logintype = logintype;
    }

    public Integer getCommodityid() {
        return commodityid;
    }

    public void setCommodityid(Integer commodityid) {
        this.commodityid = commodityid;
    }

    public String getGoodsname() {
        return goodsname;
    }

    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    public String getGoodsphoto() {
        return goodsphoto;
    }

    public void setGoodsphoto(String goodsphoto) {
        this.goodsphoto = goodsphoto;
    }

    public Integer getGoodsquantity() {
        return goodsquantity;
    }

    public void setGoodsquantity(Integer goodsquantity) {
        this.goodsquantity = goodsquantity;
    }

    public BigDecimal getGoodsweight() {
        return goodsweight;
    }

    public void setGoodsweight(BigDecimal goodsweight) {
        this.goodsweight = goodsweight;
    }

    public String getGoodsdesc() {
        return goodsdesc;
    }

    public void setGoodsdesc(String goodsdesc) {
        this.goodsdesc = goodsdesc;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public String getOrdercode() {
        return ordercode;
    }

    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode;
    }

    public String getLogisticcode() {
        return logisticcode;
    }

    public void setLogisticcode(String logisticcode) {
        this.logisticcode = logisticcode;
    }
}
