package com.paul.logisticsmanagementsystem.entity;

import java.math.BigDecimal;

/**
 * created with IntelliJ IDEA
 * User: FengZhi
 * Date: 4/21/2018
 * Time: 10:43 PM
 * Email:2045532295@qq.com
 * Addres:zhbit
 * Description:
 */
public class CompleteOrder {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderid
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.userid
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipperName
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String shippername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderCode
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String ordercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.logisticCode
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String logisticcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.senderName
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String sendername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.senderPhone
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String senderphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.senderLocation
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String senderlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.senderAddress
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String senderaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiverName
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String receivername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiverPhone
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String receiverphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiverLocation
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String receiverlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiverAddress
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String receiveraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsName
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsPhoto
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String goodsphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsQuantity
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private Integer goodsquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsWeight
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private BigDecimal goodsweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsDesc
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String goodsdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payType
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.date
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cost
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private BigDecimal cost;

    private String orderstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.state
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.remark
     *
     * @mbg.generated Fri Apr 20 14:37:46 CST 2018
     */
    private String orderremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traces.tracesid
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    private Integer tracesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traces.orderid
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traces.acceptTime
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    private String accepttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traces.AcceptStation
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    private String acceptstation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traces.Remark
     *
     * @mbg.generated Thu Apr 19 19:44:15 CST 2018
     */
    private String Remark;

    public CompleteOrder(Integer orderid, Integer userid, String shippername, String ordercode, String logisticcode, String sendername, String senderphone, String senderlocation, String senderaddress, String receivername, String receiverphone, String receiverlocation, String receiveraddress, String goodsname, String goodsphoto, Integer goodsquantity, BigDecimal goodsweight, String goodsdesc, Integer paytype, String date, BigDecimal cost,String orderstate,String state, String orderremark, Integer tracesid, String accepttime, String acceptstation, String Remark) {
        this.orderid = orderid;
        this.userid = userid;
        this.shippername = shippername;
        this.ordercode = ordercode;
        this.logisticcode = logisticcode;
        this.sendername = sendername;
        this.senderphone = senderphone;
        this.senderlocation = senderlocation;
        this.senderaddress = senderaddress;
        this.receivername = receivername;
        this.receiverphone = receiverphone;
        this.receiverlocation = receiverlocation;
        this.receiveraddress = receiveraddress;
        this.goodsname = goodsname;
        this.goodsphoto = goodsphoto;
        this.goodsquantity = goodsquantity;
        this.goodsweight = goodsweight;
        this.goodsdesc = goodsdesc;
        this.paytype = paytype;
        this.date = date;
        this.cost = cost;
        this.orderstate = orderstate;
        this.state = state;
        this.orderremark = orderremark;
        this.tracesid = tracesid;
        this.accepttime = accepttime;
        this.acceptstation = acceptstation;
        this.Remark = Remark;
    }

    public Integer getOrderid() {
        return orderid;
    }

    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getShippername() {
        return shippername;
    }

    public void setShippername(String shippername) {
        this.shippername = shippername;
    }

    public String getOrdercode() {
        return ordercode;
    }

    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode;
    }

    public String getLogisticcode() {
        return logisticcode;
    }

    public void setLogisticcode(String logisticcode) {
        this.logisticcode = logisticcode;
    }

    public String getSendername() {
        return sendername;
    }

    public void setSendername(String sendername) {
        this.sendername = sendername;
    }

    public String getSenderphone() {
        return senderphone;
    }

    public void setSenderphone(String senderphone) {
        this.senderphone = senderphone;
    }

    public String getSenderlocation() {
        return senderlocation;
    }

    public void setSenderlocation(String senderlocation) {
        this.senderlocation = senderlocation;
    }

    public String getSenderaddress() {
        return senderaddress;
    }

    public void setSenderaddress(String senderaddress) {
        this.senderaddress = senderaddress;
    }

    public String getReceivername() {
        return receivername;
    }

    public void setReceivername(String receivername) {
        this.receivername = receivername;
    }

    public String getReceiverphone() {
        return receiverphone;
    }

    public void setReceiverphone(String receiverphone) {
        this.receiverphone = receiverphone;
    }

    public String getReceiverlocation() {
        return receiverlocation;
    }

    public void setReceiverlocation(String receiverlocation) {
        this.receiverlocation = receiverlocation;
    }

    public String getReceiveraddress() {
        return receiveraddress;
    }

    public void setReceiveraddress(String receiveraddress) {
        this.receiveraddress = receiveraddress;
    }

    public String getGoodsname() {
        return goodsname;
    }

    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    public String getGoodsphoto() {
        return goodsphoto;
    }

    public void setGoodsphoto(String goodsphoto) {
        this.goodsphoto = goodsphoto;
    }

    public Integer getGoodsquantity() {
        return goodsquantity;
    }

    public void setGoodsquantity(Integer goodsquantity) {
        this.goodsquantity = goodsquantity;
    }

    public BigDecimal getGoodsweight() {
        return goodsweight;
    }

    public void setGoodsweight(BigDecimal goodsweight) {
        this.goodsweight = goodsweight;
    }

    public String getGoodsdesc() {
        return goodsdesc;
    }

    public void setGoodsdesc(String goodsdesc) {
        this.goodsdesc = goodsdesc;
    }

    public Integer getPaytype() {
        return paytype;
    }

    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public String getOrderstate() {
        return orderstate;
    }

    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getOrderremark() {
        return orderremark;
    }

    public void setOrderremark(String orderremark) {
        this.orderremark = orderremark;
    }

    public Integer getTracesid() {
        return tracesid;
    }

    public void setTracesid(Integer tracesid) {
        this.tracesid = tracesid;
    }

    public String getAccepttime() {
        return accepttime;
    }

    public void setAccepttime(String accepttime) {
        this.accepttime = accepttime;
    }

    public String getAcceptstation() {
        return acceptstation;
    }

    public void setAcceptstation(String acceptstation) {
        this.acceptstation = acceptstation;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        Remark = Remark;
    }
}
