package com.paul.logisticsmanagementsystem.entity;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsid
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.userid
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsname
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsphoto
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String goodsphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.amount
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.totalWeight
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    private String totalweight;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public Goods(Integer goodsid, Integer userid, String goodsname, String goodsphoto, String description, Integer amount, String totalweight) {
        this.goodsid = goodsid;
        this.userid = userid;
        this.goodsname = goodsname;
        this.goodsphoto = goodsphoto;
        this.description = description;
        this.amount = amount;
        this.totalweight = totalweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public Goods() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsid
     *
     * @return the value of goods.goodsid
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsid
     *
     * @param goodsid the value for goods.goodsid
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.userid
     *
     * @return the value of goods.userid
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.userid
     *
     * @param userid the value for goods.userid
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsname
     *
     * @return the value of goods.goodsname
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsname
     *
     * @param goodsname the value for goods.goodsname
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsphoto
     *
     * @return the value of goods.goodsphoto
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public String getGoodsphoto() {
        return goodsphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsphoto
     *
     * @param goodsphoto the value for goods.goodsphoto
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public void setGoodsphoto(String goodsphoto) {
        this.goodsphoto = goodsphoto == null ? null : goodsphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.amount
     *
     * @return the value of goods.amount
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.amount
     *
     * @param amount the value for goods.amount
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.totalWeight
     *
     * @return the value of goods.totalWeight
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public String getTotalweight() {
        return totalweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.totalWeight
     *
     * @param totalweight the value for goods.totalWeight
     *
     * @mbg.generated Tue Apr 03 13:54:02 CST 2018
     */
    public void setTotalweight(String totalweight) {
        this.totalweight = totalweight == null ? null : totalweight.trim();
    }
}