package com.paul.logisticsmanagementsystem.entity;

import java.math.BigDecimal;

public class OrderReservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.id
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.userid
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.shipperName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String shippername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.orderCode
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String ordercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.logisticCode
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String logisticcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.senderName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String sendername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.senderPhone
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String senderphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.senderLocation
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String senderlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.senderAddress
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String senderaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.receiverName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String receivername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.receiverPhone
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String receiverphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.receiverLocation
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String receiverlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.receiverAddress
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String receiveraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.goodsName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.goodsPhoto
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String goodsphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.goodsQuantity
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private Integer goodsquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.goodsWeight
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private BigDecimal goodsweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.goodsDesc
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String goodsdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.reserveState
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String reservestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.fetchDate
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String fetchdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.fetchStartTime
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String fetchstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.fetchEndTime
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String fetchendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.payType
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.date
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.cost
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.state
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreservation.remark
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderreservation
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public OrderReservation(Integer id, Integer userid, String shippername, String ordercode, String logisticcode, String sendername, String senderphone, String senderlocation, String senderaddress, String receivername, String receiverphone, String receiverlocation, String receiveraddress, String goodsname, String goodsphoto, Integer goodsquantity, BigDecimal goodsweight, String goodsdesc, String reservestate, String fetchdate, String fetchstarttime, String fetchendtime, String paytype, String date, BigDecimal cost, String state, String remark) {
        this.id = id;
        this.userid = userid;
        this.shippername = shippername;
        this.ordercode = ordercode;
        this.logisticcode = logisticcode;
        this.sendername = sendername;
        this.senderphone = senderphone;
        this.senderlocation = senderlocation;
        this.senderaddress = senderaddress;
        this.receivername = receivername;
        this.receiverphone = receiverphone;
        this.receiverlocation = receiverlocation;
        this.receiveraddress = receiveraddress;
        this.goodsname = goodsname;
        this.goodsphoto = goodsphoto;
        this.goodsquantity = goodsquantity;
        this.goodsweight = goodsweight;
        this.goodsdesc = goodsdesc;
        this.reservestate = reservestate;
        this.fetchdate = fetchdate;
        this.fetchstarttime = fetchstarttime;
        this.fetchendtime = fetchendtime;
        this.paytype = paytype;
        this.date = date;
        this.cost = cost;
        this.state = state;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderreservation
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public OrderReservation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.id
     *
     * @return the value of orderreservation.id
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.id
     *
     * @param id the value for orderreservation.id
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.userid
     *
     * @return the value of orderreservation.userid
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.userid
     *
     * @param userid the value for orderreservation.userid
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.shipperName
     *
     * @return the value of orderreservation.shipperName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getShippername() {
        return shippername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.shipperName
     *
     * @param shippername the value for orderreservation.shipperName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setShippername(String shippername) {
        this.shippername = shippername == null ? null : shippername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.orderCode
     *
     * @return the value of orderreservation.orderCode
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.orderCode
     *
     * @param ordercode the value for orderreservation.orderCode
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.logisticCode
     *
     * @return the value of orderreservation.logisticCode
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getLogisticcode() {
        return logisticcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.logisticCode
     *
     * @param logisticcode the value for orderreservation.logisticCode
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setLogisticcode(String logisticcode) {
        this.logisticcode = logisticcode == null ? null : logisticcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.senderName
     *
     * @return the value of orderreservation.senderName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getSendername() {
        return sendername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.senderName
     *
     * @param sendername the value for orderreservation.senderName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setSendername(String sendername) {
        this.sendername = sendername == null ? null : sendername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.senderPhone
     *
     * @return the value of orderreservation.senderPhone
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getSenderphone() {
        return senderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.senderPhone
     *
     * @param senderphone the value for orderreservation.senderPhone
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setSenderphone(String senderphone) {
        this.senderphone = senderphone == null ? null : senderphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.senderLocation
     *
     * @return the value of orderreservation.senderLocation
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getSenderlocation() {
        return senderlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.senderLocation
     *
     * @param senderlocation the value for orderreservation.senderLocation
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setSenderlocation(String senderlocation) {
        this.senderlocation = senderlocation == null ? null : senderlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.senderAddress
     *
     * @return the value of orderreservation.senderAddress
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getSenderaddress() {
        return senderaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.senderAddress
     *
     * @param senderaddress the value for orderreservation.senderAddress
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setSenderaddress(String senderaddress) {
        this.senderaddress = senderaddress == null ? null : senderaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.receiverName
     *
     * @return the value of orderreservation.receiverName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getReceivername() {
        return receivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.receiverName
     *
     * @param receivername the value for orderreservation.receiverName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setReceivername(String receivername) {
        this.receivername = receivername == null ? null : receivername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.receiverPhone
     *
     * @return the value of orderreservation.receiverPhone
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getReceiverphone() {
        return receiverphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.receiverPhone
     *
     * @param receiverphone the value for orderreservation.receiverPhone
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setReceiverphone(String receiverphone) {
        this.receiverphone = receiverphone == null ? null : receiverphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.receiverLocation
     *
     * @return the value of orderreservation.receiverLocation
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getReceiverlocation() {
        return receiverlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.receiverLocation
     *
     * @param receiverlocation the value for orderreservation.receiverLocation
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setReceiverlocation(String receiverlocation) {
        this.receiverlocation = receiverlocation == null ? null : receiverlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.receiverAddress
     *
     * @return the value of orderreservation.receiverAddress
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getReceiveraddress() {
        return receiveraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.receiverAddress
     *
     * @param receiveraddress the value for orderreservation.receiverAddress
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setReceiveraddress(String receiveraddress) {
        this.receiveraddress = receiveraddress == null ? null : receiveraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.goodsName
     *
     * @return the value of orderreservation.goodsName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.goodsName
     *
     * @param goodsname the value for orderreservation.goodsName
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.goodsPhoto
     *
     * @return the value of orderreservation.goodsPhoto
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getGoodsphoto() {
        return goodsphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.goodsPhoto
     *
     * @param goodsphoto the value for orderreservation.goodsPhoto
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setGoodsphoto(String goodsphoto) {
        this.goodsphoto = goodsphoto == null ? null : goodsphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.goodsQuantity
     *
     * @return the value of orderreservation.goodsQuantity
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public Integer getGoodsquantity() {
        return goodsquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.goodsQuantity
     *
     * @param goodsquantity the value for orderreservation.goodsQuantity
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setGoodsquantity(Integer goodsquantity) {
        this.goodsquantity = goodsquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.goodsWeight
     *
     * @return the value of orderreservation.goodsWeight
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public BigDecimal getGoodsweight() {
        return goodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.goodsWeight
     *
     * @param goodsweight the value for orderreservation.goodsWeight
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setGoodsweight(BigDecimal goodsweight) {
        this.goodsweight = goodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.goodsDesc
     *
     * @return the value of orderreservation.goodsDesc
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getGoodsdesc() {
        return goodsdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.goodsDesc
     *
     * @param goodsdesc the value for orderreservation.goodsDesc
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setGoodsdesc(String goodsdesc) {
        this.goodsdesc = goodsdesc == null ? null : goodsdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.reserveState
     *
     * @return the value of orderreservation.reserveState
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getReservestate() {
        return reservestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.reserveState
     *
     * @param reservestate the value for orderreservation.reserveState
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setReservestate(String reservestate) {
        this.reservestate = reservestate == null ? null : reservestate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.fetchDate
     *
     * @return the value of orderreservation.fetchDate
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getFetchdate() {
        return fetchdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.fetchDate
     *
     * @param fetchdate the value for orderreservation.fetchDate
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setFetchdate(String fetchdate) {
        this.fetchdate = fetchdate == null ? null : fetchdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.fetchStartTime
     *
     * @return the value of orderreservation.fetchStartTime
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getFetchstarttime() {
        return fetchstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.fetchStartTime
     *
     * @param fetchstarttime the value for orderreservation.fetchStartTime
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setFetchstarttime(String fetchstarttime) {
        this.fetchstarttime = fetchstarttime == null ? null : fetchstarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.fetchEndTime
     *
     * @return the value of orderreservation.fetchEndTime
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getFetchendtime() {
        return fetchendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.fetchEndTime
     *
     * @param fetchendtime the value for orderreservation.fetchEndTime
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setFetchendtime(String fetchendtime) {
        this.fetchendtime = fetchendtime == null ? null : fetchendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.payType
     *
     * @return the value of orderreservation.payType
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.payType
     *
     * @param paytype the value for orderreservation.payType
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.date
     *
     * @return the value of orderreservation.date
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.date
     *
     * @param date the value for orderreservation.date
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.cost
     *
     * @return the value of orderreservation.cost
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.cost
     *
     * @param cost the value for orderreservation.cost
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.state
     *
     * @return the value of orderreservation.state
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.state
     *
     * @param state the value for orderreservation.state
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreservation.remark
     *
     * @return the value of orderreservation.remark
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreservation.remark
     *
     * @param remark the value for orderreservation.remark
     *
     * @mbg.generated Wed May 23 17:33:31 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}