package com.paul.logisticsmanagementsystem.entity;

public class Sender {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sender.senderid
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    private Integer senderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sender.userid
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sender.mark
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sender.senderName
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    private String sendername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sender.senderPhone
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    private String senderphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sender.senderLocation
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    private String senderlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sender.senderAddress
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    private String senderaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public Sender(Integer senderid, Integer userid, String mark, String sendername, String senderphone, String senderlocation, String senderaddress) {
        this.senderid = senderid;
        this.userid = userid;
        this.mark = mark;
        this.sendername = sendername;
        this.senderphone = senderphone;
        this.senderlocation = senderlocation;
        this.senderaddress = senderaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sender
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public Sender() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sender.senderid
     *
     * @return the value of sender.senderid
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public Integer getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sender.senderid
     *
     * @param senderid the value for sender.senderid
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public void setSenderid(Integer senderid) {
        this.senderid = senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sender.userid
     *
     * @return the value of sender.userid
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sender.userid
     *
     * @param userid the value for sender.userid
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sender.mark
     *
     * @return the value of sender.mark
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sender.mark
     *
     * @param mark the value for sender.mark
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sender.senderName
     *
     * @return the value of sender.senderName
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public String getSendername() {
        return sendername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sender.senderName
     *
     * @param sendername the value for sender.senderName
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public void setSendername(String sendername) {
        this.sendername = sendername == null ? null : sendername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sender.senderPhone
     *
     * @return the value of sender.senderPhone
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public String getSenderphone() {
        return senderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sender.senderPhone
     *
     * @param senderphone the value for sender.senderPhone
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public void setSenderphone(String senderphone) {
        this.senderphone = senderphone == null ? null : senderphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sender.senderLocation
     *
     * @return the value of sender.senderLocation
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public String getSenderlocation() {
        return senderlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sender.senderLocation
     *
     * @param senderlocation the value for sender.senderLocation
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public void setSenderlocation(String senderlocation) {
        this.senderlocation = senderlocation == null ? null : senderlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sender.senderAddress
     *
     * @return the value of sender.senderAddress
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public String getSenderaddress() {
        return senderaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sender.senderAddress
     *
     * @param senderaddress the value for sender.senderAddress
     *
     * @mbg.generated Thu Apr 19 20:22:55 CST 2018
     */
    public void setSenderaddress(String senderaddress) {
        this.senderaddress = senderaddress == null ? null : senderaddress.trim();
    }
}