package com.paul.logisticsmanagementsystem.entity;

import java.util.ArrayList;
import java.util.List;

public class SubMenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public SubMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubmenuidIsNull() {
            addCriterion("submenuid is null");
            return (Criteria) this;
        }

        public Criteria andSubmenuidIsNotNull() {
            addCriterion("submenuid is not null");
            return (Criteria) this;
        }

        public Criteria andSubmenuidEqualTo(Integer value) {
            addCriterion("submenuid =", value, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidNotEqualTo(Integer value) {
            addCriterion("submenuid <>", value, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidGreaterThan(Integer value) {
            addCriterion("submenuid >", value, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("submenuid >=", value, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidLessThan(Integer value) {
            addCriterion("submenuid <", value, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidLessThanOrEqualTo(Integer value) {
            addCriterion("submenuid <=", value, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidIn(List<Integer> values) {
            addCriterion("submenuid in", values, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidNotIn(List<Integer> values) {
            addCriterion("submenuid not in", values, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidBetween(Integer value1, Integer value2) {
            addCriterion("submenuid between", value1, value2, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenuidNotBetween(Integer value1, Integer value2) {
            addCriterion("submenuid not between", value1, value2, "submenuid");
            return (Criteria) this;
        }

        public Criteria andSubmenunameIsNull() {
            addCriterion("submenuname is null");
            return (Criteria) this;
        }

        public Criteria andSubmenunameIsNotNull() {
            addCriterion("submenuname is not null");
            return (Criteria) this;
        }

        public Criteria andSubmenunameEqualTo(String value) {
            addCriterion("submenuname =", value, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameNotEqualTo(String value) {
            addCriterion("submenuname <>", value, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameGreaterThan(String value) {
            addCriterion("submenuname >", value, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameGreaterThanOrEqualTo(String value) {
            addCriterion("submenuname >=", value, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameLessThan(String value) {
            addCriterion("submenuname <", value, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameLessThanOrEqualTo(String value) {
            addCriterion("submenuname <=", value, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameLike(String value) {
            addCriterion("submenuname like", value, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameNotLike(String value) {
            addCriterion("submenuname not like", value, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameIn(List<String> values) {
            addCriterion("submenuname in", values, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameNotIn(List<String> values) {
            addCriterion("submenuname not in", values, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameBetween(String value1, String value2) {
            addCriterion("submenuname between", value1, value2, "submenuname");
            return (Criteria) this;
        }

        public Criteria andSubmenunameNotBetween(String value1, String value2) {
            addCriterion("submenuname not between", value1, value2, "submenuname");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table submenu
     *
     * @mbg.generated do_not_delete_during_merge Tue May 15 11:28:58 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}