package com.paul.logisticsmanagementsystem.entity;

public class SubMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.submenuid
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    private Integer submenuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.submenuname
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    private String submenuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.url
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submenu.status
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public SubMenu(Integer submenuid, String submenuname, String url, String status) {
        this.submenuid = submenuid;
        this.submenuname = submenuname;
        this.url = url;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submenu
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public SubMenu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.submenuid
     *
     * @return the value of submenu.submenuid
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public Integer getSubmenuid() {
        return submenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.submenuid
     *
     * @param submenuid the value for submenu.submenuid
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public void setSubmenuid(Integer submenuid) {
        this.submenuid = submenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.submenuname
     *
     * @return the value of submenu.submenuname
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public String getSubmenuname() {
        return submenuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.submenuname
     *
     * @param submenuname the value for submenu.submenuname
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public void setSubmenuname(String submenuname) {
        this.submenuname = submenuname == null ? null : submenuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.url
     *
     * @return the value of submenu.url
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.url
     *
     * @param url the value for submenu.url
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submenu.status
     *
     * @return the value of submenu.status
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submenu.status
     *
     * @param status the value for submenu.status
     *
     * @mbg.generated Tue May 15 11:28:58 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}