package com.paul.logisticsmanagementsystem.entity;

public class TracesReservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracesreservation.tracesid
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    private Integer tracesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracesreservation.id
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracesreservation.acceptTime
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    private String accepttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracesreservation.AcceptStation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    private String acceptstation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracesreservation.Remark
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public TracesReservation(Integer tracesid, Integer id, String accepttime, String acceptstation, String remark) {
        this.tracesid = tracesid;
        this.id = id;
        this.accepttime = accepttime;
        this.acceptstation = acceptstation;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public TracesReservation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracesreservation.tracesid
     *
     * @return the value of tracesreservation.tracesid
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public Integer getTracesid() {
        return tracesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracesreservation.tracesid
     *
     * @param tracesid the value for tracesreservation.tracesid
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void setTracesid(Integer tracesid) {
        this.tracesid = tracesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracesreservation.id
     *
     * @return the value of tracesreservation.id
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracesreservation.id
     *
     * @param id the value for tracesreservation.id
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracesreservation.acceptTime
     *
     * @return the value of tracesreservation.acceptTime
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public String getAccepttime() {
        return accepttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracesreservation.acceptTime
     *
     * @param accepttime the value for tracesreservation.acceptTime
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void setAccepttime(String accepttime) {
        this.accepttime = accepttime == null ? null : accepttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracesreservation.AcceptStation
     *
     * @return the value of tracesreservation.AcceptStation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public String getAcceptstation() {
        return acceptstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracesreservation.AcceptStation
     *
     * @param acceptstation the value for tracesreservation.AcceptStation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void setAcceptstation(String acceptstation) {
        this.acceptstation = acceptstation == null ? null : acceptstation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracesreservation.Remark
     *
     * @return the value of tracesreservation.Remark
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracesreservation.Remark
     *
     * @param remark the value for tracesreservation.Remark
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}