package com.paul.logisticsmanagementsystem.entity;

import java.util.ArrayList;
import java.util.List;

public class TracesReservationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public TracesReservationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTracesidIsNull() {
            addCriterion("tracesid is null");
            return (Criteria) this;
        }

        public Criteria andTracesidIsNotNull() {
            addCriterion("tracesid is not null");
            return (Criteria) this;
        }

        public Criteria andTracesidEqualTo(Integer value) {
            addCriterion("tracesid =", value, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidNotEqualTo(Integer value) {
            addCriterion("tracesid <>", value, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidGreaterThan(Integer value) {
            addCriterion("tracesid >", value, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tracesid >=", value, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidLessThan(Integer value) {
            addCriterion("tracesid <", value, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidLessThanOrEqualTo(Integer value) {
            addCriterion("tracesid <=", value, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidIn(List<Integer> values) {
            addCriterion("tracesid in", values, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidNotIn(List<Integer> values) {
            addCriterion("tracesid not in", values, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidBetween(Integer value1, Integer value2) {
            addCriterion("tracesid between", value1, value2, "tracesid");
            return (Criteria) this;
        }

        public Criteria andTracesidNotBetween(Integer value1, Integer value2) {
            addCriterion("tracesid not between", value1, value2, "tracesid");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccepttimeIsNull() {
            addCriterion("acceptTime is null");
            return (Criteria) this;
        }

        public Criteria andAccepttimeIsNotNull() {
            addCriterion("acceptTime is not null");
            return (Criteria) this;
        }

        public Criteria andAccepttimeEqualTo(String value) {
            addCriterion("acceptTime =", value, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeNotEqualTo(String value) {
            addCriterion("acceptTime <>", value, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeGreaterThan(String value) {
            addCriterion("acceptTime >", value, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeGreaterThanOrEqualTo(String value) {
            addCriterion("acceptTime >=", value, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeLessThan(String value) {
            addCriterion("acceptTime <", value, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeLessThanOrEqualTo(String value) {
            addCriterion("acceptTime <=", value, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeLike(String value) {
            addCriterion("acceptTime like", value, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeNotLike(String value) {
            addCriterion("acceptTime not like", value, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeIn(List<String> values) {
            addCriterion("acceptTime in", values, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeNotIn(List<String> values) {
            addCriterion("acceptTime not in", values, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeBetween(String value1, String value2) {
            addCriterion("acceptTime between", value1, value2, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAccepttimeNotBetween(String value1, String value2) {
            addCriterion("acceptTime not between", value1, value2, "accepttime");
            return (Criteria) this;
        }

        public Criteria andAcceptstationIsNull() {
            addCriterion("AcceptStation is null");
            return (Criteria) this;
        }

        public Criteria andAcceptstationIsNotNull() {
            addCriterion("AcceptStation is not null");
            return (Criteria) this;
        }

        public Criteria andAcceptstationEqualTo(String value) {
            addCriterion("AcceptStation =", value, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationNotEqualTo(String value) {
            addCriterion("AcceptStation <>", value, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationGreaterThan(String value) {
            addCriterion("AcceptStation >", value, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationGreaterThanOrEqualTo(String value) {
            addCriterion("AcceptStation >=", value, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationLessThan(String value) {
            addCriterion("AcceptStation <", value, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationLessThanOrEqualTo(String value) {
            addCriterion("AcceptStation <=", value, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationLike(String value) {
            addCriterion("AcceptStation like", value, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationNotLike(String value) {
            addCriterion("AcceptStation not like", value, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationIn(List<String> values) {
            addCriterion("AcceptStation in", values, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationNotIn(List<String> values) {
            addCriterion("AcceptStation not in", values, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationBetween(String value1, String value2) {
            addCriterion("AcceptStation between", value1, value2, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andAcceptstationNotBetween(String value1, String value2) {
            addCriterion("AcceptStation not between", value1, value2, "acceptstation");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tracesreservation
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 30 13:40:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tracesreservation
     *
     * @mbg.generated Mon Apr 30 13:40:31 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}